openapi: 3.0.1
info:
  title: Closest Holiday Service API
  description: API to find closest Holiday
  version: 0.0.1
servers:
  - url: https://localhost:50000
    description: The server
tags:
  - name: holiday
paths:

  /demo/holiday:
    get:
      tags:
        - holiday
      description: 'Return closest holiday'
      summary: 'Returns the closest holiday for the provided date'
      operationId: getClosestHoliday
      parameters:
        - name: country
          description: 'For countries, ISO 3166-1 alpha-2 or ISO 3166-1 alpha-3 format. For subdivisions, ISO 3166-2 format. Accepts up to 10 comma separated values.'
          required: true
          in: query
          schema:
            type: string
          example: US
        - name: date
          description: 'Input date near which a holiday has to be searched'
          required: false
          in: query
          schema:
            type: string
            format: date
            example: '2015-07-04'
      responses:
        '200':
          description: 'Success! Everything is A-OK.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Holiday'

components:
  schemas:
    Holiday:
      type: object
      properties:
        nearestHolidayDate:
          type: string
          format: date
          example: '2021-12-25'
        holidayName:
          type: string
          example: 'Christmas Day'